-- Table pour stocker les rapports météo
CREATE TABLE WEATHER_REPORT (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    latitude NUMBER(10, 6) NOT NULL,
    longitude NUMBER(10, 6) NOT NULL,
    condition VARCHAR2(50) NOT NULL,
    temperature NUMBER(5, 2),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Donne un quota si nécessaire (à exécuter avec un compte admin)
-- ALTER USER MOMO QUOTA UNLIMITED ON USERS;

-- Exemple d'insertion
INSERT INTO WEATHER_REPORT (latitude, longitude, condition, temperature)
VALUES (48.8566, 2.3522, 'Sunny', 25.5);
